import i18n from '../i18n';

const states = [
  { abbr: 'AL', name: i18n.t('Alabama') },
  { abbr: 'AK', name: i18n.t('Alaska') },
  { abbr: 'AZ', name: i18n.t('Arizona') },
  { abbr: 'AR', name: i18n.t('Arkansas') },
  { abbr: 'CA', name: i18n.t('California') },
  { abbr: 'CO', name: i18n.t('Colorado') },
  { abbr: 'CT', name: i18n.t('Connecticut') },
  { abbr: 'DE', name: i18n.t('Delaware') },
  { abbr: 'DC', name: i18n.t('District Of Columbia') },
  { abbr: 'FL', name: i18n.t('Florida') },
  { abbr: 'GA', name: i18n.t('Georgia') },
  { abbr: 'HI', name: i18n.t('Hawaii') },
  { abbr: 'ID', name: i18n.t('Idaho') },
  { abbr: 'IL', name: i18n.t('Illinois') },
  { abbr: 'IN', name: i18n.t('Indiana') },
  { abbr: 'IA', name: i18n.t('Iowa') },
  { abbr: 'KS', name: i18n.t('Kansas') },
  { abbr: 'KY', name: i18n.t('Kentucky') },
  { abbr: 'LA', name: i18n.t('Louisiana') },
  { abbr: 'ME', name: i18n.t('Maine') },
  { abbr: 'MD', name: i18n.t('Maryland') },
  { abbr: 'MA', name: i18n.t('Massachusetts') },
  { abbr: 'MI', name: i18n.t('Michigan') },
  { abbr: 'MN', name: i18n.t('Minnesota') },
  { abbr: 'MS', name: i18n.t('Mississippi') },
  { abbr: 'MO', name: i18n.t('Missouri') },
  { abbr: 'MT', name: i18n.t('Montana') },
  { abbr: 'NE', name: i18n.t('Nebraska') },
  { abbr: 'NV', name: i18n.t('Nevada') },
  { abbr: 'NH', name: i18n.t('New Hampshire') },
  { abbr: 'NJ', name: i18n.t('New Jersey') },
  { abbr: 'NM', name: i18n.t('New Mexico') },
  { abbr: 'NY', name: i18n.t('New York') },
  { abbr: 'NC', name: i18n.t('North Carolina') },
  { abbr: 'ND', name: i18n.t('North Dakota') },
  { abbr: 'OH', name: i18n.t('Ohio') },
  { abbr: 'OK', name: i18n.t('Oklahoma') },
  { abbr: 'OR', name: i18n.t('Oregon') },
  { abbr: 'PA', name: i18n.t('Pennsylvania') },
  { abbr: 'RI', name: i18n.t('Rhode Island') },
  { abbr: 'SC', name: i18n.t('South Carolina') },
  { abbr: 'SD', name: i18n.t('South Dakota') },
  { abbr: 'TN', name: i18n.t('Tennessee') },
  { abbr: 'TX', name: i18n.t('Texas') },
  { abbr: 'UT', name: i18n.t('Utah') },
  { abbr: 'VT', name: i18n.t('Vermont') },
  { abbr: 'VA', name: i18n.t('Virginia') },
  { abbr: 'WA', name: i18n.t('Washington') },
  { abbr: 'WV', name: i18n.t('West Virginia') },
  { abbr: 'WI', name: i18n.t('Wisconsin') },
  { abbr: 'WY', name: i18n.t('Wyoming') },
  { abbr: 'PR', name: i18n.t('Puerto Rico') }
];

export default states;
